// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdjiM6tvkhaPVTMIxu4xZ_ihPwRRoQQ-o',
    appId: '1:236175446129:web:2126857467d5b470de8bd0',
    messagingSenderId: '236175446129',
    projectId: 'mind-mate-43111',
    authDomain: 'mind-mate-43111.firebaseapp.com',
    storageBucket: 'mind-mate-43111.firebasestorage.app',
    measurementId: 'G-4WG9L5RDZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgu3e9AdS_5LLdWVEiX56StHfVq5vphWA',
    appId: '1:236175446129:android:76b9fffb1b0b29bbde8bd0',
    messagingSenderId: '236175446129',
    projectId: 'mind-mate-43111',
    storageBucket: 'mind-mate-43111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATDgS90bqvo2I9HxkhN2Ri-iQfoUIW8I0',
    appId: '1:236175446129:ios:7f145ce6755f10c8de8bd0',
    messagingSenderId: '236175446129',
    projectId: 'mind-mate-43111',
    storageBucket: 'mind-mate-43111.firebasestorage.app',
    iosBundleId: 'com.yourname.myAppNew',
  );
}
